"""add study.title column

Revision ID: 4be44a0a2a37
Revises: ee05c8792da0
Create Date: 2026-08-04 01:35:58.264373
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401  (autogen emits postgresql.JSONB)

revision: str = '4be44a0a2a37'
down_revision: str | None = 'ee05c8792da0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'title')
    # ### end Alembic commands ###
