"""add content and media_type columns to asset

Revision ID: bccbb04a89c8
Revises: d1a2b3c4d5e6
Create Date: 2026-09-17 19:35:20.394133
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401  (autogen emits postgresql.JSONB)

revision: str = 'bccbb04a89c8'
down_revision: str | None = 'd1a2b3c4d5e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True))
    op.add_column('asset', sa.Column('content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'content')
    op.drop_column('asset', 'media_type')
    # ### end Alembic commands ###
