"""initial schema

Revision ID: ee05c8792da0
Revises: 
Create Date: 2026-08-03 20:48:20.652013
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401  (autogen emits postgresql.JSONB)

revision: str = 'ee05c8792da0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('testament', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_code'), 'book', ['code'], unique=False)
    op.create_index(op.f('ix_book_number'), 'book', ['number'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_study_id'), 'event', ['study_id'], unique=False)
    op.create_index(op.f('ix_event_ts'), 'event', ['ts'], unique=False)
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_setting_user_key')
    )
    op.create_index(op.f('ix_setting_key'), 'setting', ['key'], unique=False)
    op.create_index(op.f('ix_setting_user_id'), 'setting', ['user_id'], unique=False)
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('minutes_per_day', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('tradition', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('imagery_policy', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('primary_translation', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('outline_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_user_id'), 'study', ['user_id'], unique=False)
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('license_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('verse_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_code'), 'translation', ['code'], unique=True)
    op.create_table('usage_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('job_kind', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_ledger_study_id'), 'usage_ledger', ['study_id'], unique=False)
    op.create_index(op.f('ix_usage_ledger_ts'), 'usage_ledger', ['ts'], unique=False)
    op.create_index(op.f('ix_usage_ledger_user_id'), 'usage_ledger', ['user_id'], unique=False)
    op.create_table('study_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('blocks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_summary', sqlmodel.sql.sqltypes.AutoString(length=1200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'day_number', name='uq_study_day')
    )
    op.create_index(op.f('ix_study_day_study_id'), 'study_day', ['study_id'], unique=False)
    op.create_table('verse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('book_number', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('words_of_jesus', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['translation_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('translation_id', 'book_number', 'chapter', 'verse', name='uq_verse_location')
    )
    op.create_index(op.f('ix_verse_book_number'), 'verse', ['book_number'], unique=False)
    op.create_index('ix_verse_lookup', 'verse', ['translation_id', 'book_number', 'chapter'], unique=False)
    op.create_index(op.f('ix_verse_translation_id'), 'verse', ['translation_id'], unique=False)
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('study_day_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_day_id'], ['study_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_study_day_id'), 'asset', ['study_day_id'], unique=False)
    op.create_index(op.f('ix_asset_user_id'), 'asset', ['user_id'], unique=False)
    op.create_table('day_passage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_day_id', sa.Integer(), nullable=False),
    sa.Column('ref_book', sa.Integer(), nullable=False),
    sa.Column('ref_chapter', sa.Integer(), nullable=False),
    sa.Column('ref_verse_start', sa.Integer(), nullable=False),
    sa.Column('ref_verse_end', sa.Integer(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(length=800), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['study_day_id'], ['study_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_passage_study_day_id'), 'day_passage', ['study_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_passage_study_day_id'), table_name='day_passage')
    op.drop_table('day_passage')
    op.drop_index(op.f('ix_asset_user_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_study_day_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_verse_translation_id'), table_name='verse')
    op.drop_index('ix_verse_lookup', table_name='verse')
    op.drop_index(op.f('ix_verse_book_number'), table_name='verse')
    op.drop_table('verse')
    op.drop_index(op.f('ix_study_day_study_id'), table_name='study_day')
    op.drop_table('study_day')
    op.drop_index(op.f('ix_usage_ledger_user_id'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_ts'), table_name='usage_ledger')
    op.drop_index(op.f('ix_usage_ledger_study_id'), table_name='usage_ledger')
    op.drop_table('usage_ledger')
    op.drop_index(op.f('ix_translation_code'), table_name='translation')
    op.drop_table('translation')
    op.drop_index(op.f('ix_study_user_id'), table_name='study')
    op.drop_table('study')
    op.drop_index(op.f('ix_setting_user_id'), table_name='setting')
    op.drop_index(op.f('ix_setting_key'), table_name='setting')
    op.drop_table('setting')
    op.drop_index(op.f('ix_event_ts'), table_name='event')
    op.drop_index(op.f('ix_event_study_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_book_number'), table_name='book')
    op.drop_index(op.f('ix_book_code'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
