import pathlib

lines = []
lines.append('"""TTS endpoint behaviour + async edge-tts render path (mocked).')
lines.append('')
lines.append('Covers auth, ownership, day-content, and asset lifecycle paths.')
lines.append('"""')
lines.append('from __future__ import annotations')
lines.append('')
lines.append('import time')
lines.append('from pathlib import Path')
lines.append('from unittest.mock import patch')
lines.append('')
lines.append('import pytest')
lines.append('from fastapi.testclient import TestClient')
lines.append('from sqlmodel import Session, select')
lines.append('')
lines.append('from app.models import Asset, Study, StudyDay')
lines.append('from app.tests.conftest import direct_session')
lines.append('')
lines.append('')
lines.append('def _make_owned_study(client: TestClient, topic: str = "Test",')
lines.append('                       total_days: int = 1) -> Study:')
lines.append('    with direct_session(client) as s:')
lines.append('        study = Study(topic=topic, minutes_per_day=15,')
lines.append('                      total_days=total_days,')
lines.append('                      tradition="non_denominational",')
lines.append('                      primary_translation="KJV",')
lines.append('                      status="ready", user_id=1)')
lines.append('        s.add(study)')
lines.append('        s.commit()')
lines.append('        s.refresh(study)')
lines.append('        return study')
lines.append('')
lines.append('')
lines.append('def _seed_day_with_content(client: TestClient, study: Study,')
lines.append('                            day_number: int = 1) -> StudyDay:')
lines.append('    with direct_session(client) as s:')
lines.append('        day = StudyDay(study_id=study.id, day_number=day_number,')
lines.append('                       status="ready",')
lines.append('                       blocks_json={')
lines.append('                           "opening_prayer":')
lines.append('                           "Heavenly Father, bless this study.",')
lines.append('                           "commentary":')
lines.append('                           "Grace and truth came through Jesus Christ.",')
lines.append('                           "questions": ["What does grace mean?"],')
lines.append('                           "closing_prayer": "Amen.",')
lines.append('                       })')
lines.append('        s.add(day)')
lines.append('        s.commit()')
lines.append('        s.refresh(day)')
lines.append('        return day')
lines.append('')
lines.append('')
lines.append('_MP3 = b"\\x00\\x00\\x00\\x00" + b"\\x00" * 64')
lines.append('')
lines.append('')
lines.append('class _FakeVC:')
lines.append('    def __init__(self, *args, **kwargs):')
lines.append('        pass')
lines.append('')
lines.append('    async def save(self, path: str) -> None:')
lines.append('        Path(path).write_bytes(_MP3)')
lines.append('')
lines.append('')
lines.append('@pytest.fixture(autouse=True)')
lines.append('def _reset_voices():')
lines.append('    import app.routers.tts as tts_mod')
lines.append('    tts_mod._voices = None')
lines.append('    yield')
lines.append('')
lines.append('')
lines.append('def test_voices_returns_list_when_edge_available(')
lines.append('        client: TestClient) -> None:')
lines.append('    with patch("app.routers.tts._edge_voices",')
lines.append('               return_value=[{"short_name": "en-AU-NatashaNeural",')
lines.append('                              "gender": "Female",')
lines.append('                              "friendly_name": "Microsoft Natasha",')
lines.append('                              "locale": "en-AU"}]):')
lines.append('        r = client.get("/api/tts/voices")')
lines.append('    assert r.status_code == 200')
lines.append('    body = r.json()')
lines.append('    assert body["count"] == 1')
lines.append('    assert body["voices"][0]["short_name"] == "en-AU-NatashaNeural"')
lines.append('')
lines.append('')
lines.append('def test_voices_empty_when_edge_unavailable(client: TestClient)')
lines.append('-> None:')
lines.append('    with patch("app.routers.tts._edge_voices", return_value=[]):')
lines.append('        r = client.get("/api/tts/voices")')
lines.append('    assert r.status_code == 200')
lines.append('    assert r.json()["count"] == 0')
lines.append('')
lines.append('')
lines.append('def test_render_requires_auth(anon_client: TestClient) -> None:')
lines.append('    r = anon_client.post("/api/tts/render", json={')
lines.append('        "study_id": 1, "day_number": 1,')
lines.append('        "voice": "en-AU-NatashaNeural",')
lines.append('    })')
lines.append('    assert r.status_code == 401')
lines.append('    assert "missing" in r.json()["detail"].lower() or')
lines.append('           "authorization" in r.json()["detail"].lower() or')
lines.append('           "credential" in r.json()["detail"].lower()')
lines.append('')
lines.append('')
lines.append('def test_render_rejects_unknown_study(client: TestClient) -> None:')
lines.append('    r = client.post("/api/tts/render", json={')
lines.append('        "study_id": 99999, "day_number": 1,')
lines.append('        "voice": "en-AU-NatashaNeural",')
lines.append('    })')
lines.append('    assert r.status_code == 404')
lines.append('')
lines.append('')
lines.append('def test_render_rejects_day_out_of_range(client: TestClient) -> None:')
lines.append('    study = _make_owned_study(client, total_days=2)')
lines.append('    _seed_day_with_content(client, study, 1)')
lines.append('    _seed_day_with_content(client, study, 2)')
lines.append('    r = client.post("/api/tts/render", json={')
lines.append('        "study_id": study.id, "day_number": 3,')
lines.append('        "voice": "en-AU-NatashaNeural",')
lines.append('    })')
lines.append('    assert r.status_code == 400')
lines.append('')
lines.append('')
lines.append('def test_render_rejects_empty_day(client: TestClient) -> None:')
lines.append('    study = _make_owned_study(client)')
lines.append('    day = _seed_day_with_content(client, study)')
lines.append('    with direct_session(client) as s:')
lines.append('        d = s.get(StudyDay, day.id)')
lines.append('        d.blocks_json["opening_prayer"] = ""')
lines.append('        d.blocks_json["commentary"] = ""')
lines.append('        d.blocks_json["questions"] = []')
lines.append('        d.blocks_json["closing_prayer"] = ""')
lines.append('        s.add(d)')
lines.append('        s.commit()')
lines.append('    r = client.post("/api/tts/render", json={')
lines.append('        "study_id": study.id, "day_number": 1,')
lines.append('        "voice": "en-AU-NatashaNeural",')
lines.append('    })')
lines.append('    assert r.status_code == 400')
lines.append('')
lines.append('')
lines.append('def test_render_rejects_unknown_voice(client: TestClient) -> None:')
lines.append('    study = _make_owned_study(client)')
lines.append('    _seed_day_with_content(client, study)')
lines.append('    r = client.post("/api/tts/render", json={')
lines.append('        "study_id": study.id, "day_number": 1,')
lines.append('        "voice": "unlikely-voice-short-name",')
lines.append('    })')
lines.append('    assert r.status_code == 400')
lines.append('')
lines.append('')
lines.append('def test_render_creates_rendering_asset(client: TestClient) -> None:')
lines.append('    study = _make_owned_study(client)')
lines.append('    _seed_day_with_content(client, study)')
lines.append('    with patch("app.routers.tts._edge_voices",')
lines.append('               return_value=[{"short_name": "en-AU-NatashaNeural",')
lines.append('                              "gender": "Female",')
lines.append('                              "friendly_name": "Microsoft Natasha",')
lines.append('                              "locale": "en-AU"}]):')
lines.append('        r = client.post("/api/tts/render", json={')
lines.append('            "study_id": study.id, "day_number": 1,')
lines.append('            "voice": "en-AU-NatashaNeural",')
lines.append('        })')
lines.append('    assert r.status_code == 202')
lines.append('    body = r.json()')
lines.append('    assert body["status"] == "rendering"')
lines.append('    asset_id = body["asset_id"]')
lines.append('    with direct_session(client) as s:')
lines.append('        asset = s.get(Asset, asset_id)')
lines.append('    assert asset is not None')
lines.append('    assert asset.status == "rendering"')
lines.append('    assert asset.kind == "audio"')
lines.append('    assert asset.provider == "edge-tts"')
lines.append('    assert asset.model == "en-AU-NatashaNeural"')
lines.append('')
lines.append('')
lines.append('def test_render_happy_path_writes_mp3_to_asset(')
lines.append('        client: TestClient) -> None:')
lines.append('    study = _make_owned_study(client)')
lines.append('    _seed_day_with_content(client, study)')
lines.append('    with patch("app.routers.tts._edge_voices",')
lines.append('               return_value=[{"short_name": "en-AU-NatashaNeural",')
lines.append('                              "gender": "Female",')
lines.append('                              "friendly_name": "Microsoft Natasha",')
lines.append('                              "locale": "en-AU"}]),')
lines.append('         patch("app.routers.tts.edge_tts.Communicate", _FakeVC):')
lines.append('        r = client.post("/api/tts/render", json={')
lines.append('            "study_id": study.id, "day_number": 1,')
lines.append('            "voice": "en-AU-NatashaNeural",')
lines.append('        })')
lines.append('    assert r.status_code == 202')
lines.append('    asset_id = r.json()["asset_id"]')
lines.append('    for _ in range(60):')
lines.append('        with direct_session(client) as s:')
lines.append('            asset = s.get(Asset, asset_id)')
lines.append('        if asset is not None and asset.status != "rendering":')
lines.append('            break')
lines.append('        time.sleep(0.05)')
lines.append('    with direct_session(client) as s:')
lines.append('        asset = s.get(Asset, asset_id)')
lines.append('    assert asset is not None')
lines.append('    assert asset.status == "ready"')
lines.append('    assert asset.media_type == "audio/mpeg"')
lines.append('    assert asset.content == _MP3')
lines.append('')
lines.append('')
lines.append('def test_asset_ready_serves_mp3(client: TestClient) -> None:')
lines.append('    study = _make_owned_study(client)')
lines.append('    day = _seed_day_with_content(client, study)')
lines.append('    with direct_session(client) as s:')
lines.append('        asset = Asset(study_day_id=day.id, kind="audio",')
lines.append('                      provider="edge-tts",')
lines.append('                      model="en-AU-NatashaNeural",')
lines.append('                      prompt="", status="ready",')
lines.append('                      error="", media_type="audio/mpeg",')
lines.append('                      content=_MP3)')
lines.append('        s.add(asset)')
lines.append('        s.commit()')
lines.append('        s.refresh(asset)')
lines.append('        asset_id = asset.id')
lines.append('    r = client.get(f"/api/tts/asset/{asset_id}")')
lines.append('    assert r.status_code == 200')
lines.append('    assert r.content == _MP3')
lines.append('    assert r.headers["content-type"] == "audio/mpeg"')
lines.append('    assert "tts-" in r.headers["content-disposition"]')
lines.append('')
lines.append('')
lines.append('def test_asset_poll_returns_202_while_rendering(')
lines.append('        client: TestClient) -> None:')
lines.append('    study = _make_owned_study(client)')
lines.append('    day = _seed_day_with_content(client, study)')
lines.append('    with direct_session(client) as s:')
lines.append('        asset = Asset(study_day_id=day.id, kind="audio",')
lines.append('                      provider="edge-tts",')
lines.append('                      model="en-AU-NatashaNeural",')
lines.append('                      prompt="", status="rendering",')
lines.append('                      error="", media_type="", content=b"")')
lines.append('        s.add(asset)')
lines.append('        s.commit()')
lines.append('        s.refresh(asset)')
lines.append('        asset_id = asset.id')
lines.append('    r = client.get(f"/api/tts/asset/{asset_id}")')
lines.append('    assert r.status_code == 202')
lines.append('')
lines.append('')
lines.append('def test_asset_failed_returns_409_with_error(')
lines.append('        client: TestClient) -> None:')
lines.append('    study = _make_owned_study(client)')
lines.append('    day = _seed_day_with_content(client, study)')
lines.append('    with direct_session(client) as s:')
lines.append('        asset = Asset(study_day_id=day.id, kind="audio",')
lines.append('                      provider="edge-tts",')
lines.append('                      model="en-AU-NatashaNeural",')
lines.append('                      prompt="", status="failed",')
lines.append('                      error="WSServerHandshakeError: 403",')
lines.append('                      media_type="", content=b"")')
lines.append('        s.add(asset)')
lines.append('        s.commit()')
lines.append('        s.refresh(asset)')
lines.append('        asset_id = asset.id')
lines.append('    r = client.get(f"/api/tts/asset/{asset_id}")')
lines.append('    assert r.status_code == 409')
lines.append('    assert "403" in r.json()["detail"]')
lines.append('')
lines.append('')
lines.append('def test_asset_unknown_is_404(client: TestClient) -> None:')
lines.append('    r = client.get("/api/tts/asset/99999")')
lines.append('    assert r.status_code == 404')
lines.append('')
lines.append('')
lines.append('def test_asset_belonging_to_other_study_is_404(')
lines.append('        client: TestClient) -> None:')
lines.append('    other = _make_owned_study(client, topic="Other")')
lines.append('    day = _seed_day_with_content(client, other)')
lines.append('    with direct_session(client) as s:')
lines.append('        asset = Asset(study_day_id=day.id, kind="audio",')
lines.append('                      provider="edge-tts",')
lines.append('                      model="en-AU-NatashaNeural",')
lines.append('                      prompt="", status="ready",')
lines.append('                      error="", media_type="audio/mpeg",')
lines.append('                      content=_MP3)')
lines.append('        s.add(asset)')
lines.append('        s.commit()')
lines.append('        s.refresh(asset)')
lines.append('        asset_id = asset.id')
lines.append('    r = client.get(f"/api/tts/asset/{asset_id}")')
lines.append('    assert r.status_code == 404')
lines.append('')

pathlib.Path("tests/test_tts.py").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("written", len("\n".join(lines)), "bytes")

