/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Parchment & Ink — Modern Academic Scripture System
        background: '#f8f9ff',
        on_background: '#0b1c30',
        surface: '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-variant': '#d3e4fe',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#43474c',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#74777d',
        'outline-variant': '#c4c6cd',
        'surface-tint': '#4e6073',
        primary: '#162839',
        'on-primary': '#ffffff',
        'primary-container': '#2c3e50',
        'on-primary-container': '#96a9be',
        'inverse-primary': '#b5c8df',
        'primary-fixed': '#d1e4fb',
        'primary-fixed-dim': '#b5c8df',
        'on-primary-fixed': '#091d2e',
        'on-primary-fixed-variant': '#36485b',
        secondary: '#5e5f56',
        'on-secondary': '#ffffff',
        'secondary-container': '#e4e3d7',
        'on-secondary-container': '#64655c',
        'secondary-fixed': '#e4e3d7',
        'secondary-fixed-dim': '#c7c7bc',
        'on-secondary-fixed': '#1b1c15',
        'on-secondary-fixed-variant': '#46473f',
        tertiary: '#342400',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#503800',
        'on-tertiary-container': '#c7a15a',
        'tertiary-fixed': '#ffdea5',
        'tertiary-fixed-dim': '#e9c176',
        'on-tertiary-fixed': '#261900',
        'on-tertiary-fixed-variant': '#5d4201',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        // The Scholar (scripture, headings) + The Librarian (UI)
        'display-scripture': ['"EB Garamond"', 'Georgia', 'serif'],
        'headline-lg': ['"EB Garamond"', 'Georgia', 'serif'],
        'headline-md': ['"EB Garamond"', 'Georgia', 'serif'],
        'body-reading': ['"EB Garamond"', 'Georgia', 'serif'],
        'ui-label-lg': ['Inter', 'system-ui', 'sans-serif'],
        'ui-label-md': ['Inter', 'system-ui', 'sans-serif'],
        'ui-label-sm': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-scripture': ['34px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'body-reading': ['20px', { lineHeight: '32px', fontWeight: '400' }],
        'ui-label-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.02em', fontWeight: '600' }],
        'ui-label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'ui-label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'ui-label-xs': ['11px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-max': '1200px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'reading-width': '720px',
      },
      maxWidth: {
        'container-max': '1200px',
        'reading-width': '720px',
      },
      boxShadow: {
        'ambient': '0 4px 20px rgba(44, 62, 80, 0.05)',
        'ambient-lg': '0 8px 30px rgba(44, 62, 80, 0.08)',
        'ambient-top': '0 -10px 40px rgba(22, 40, 57, 0.05)',
      },
    },
  },
  plugins: [],
}
