/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // Dynamic Theme System (Parchment & Ink Light / Midnight Sanctuary Dark)
        background: 'var(--color-background)',
        on_background: 'var(--color-on-background)',
        surface: 'var(--color-surface)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-tint': 'var(--color-surface-tint)',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        secondary: 'var(--color-secondary)',
        'on-secondary': 'var(--color-on-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        tertiary: 'var(--color-tertiary)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        error: 'var(--color-error)',
        'on-error': 'var(--color-on-error)',
        'error-container': 'var(--color-error-container)',
        'on-error-container': 'var(--color-on-error-container)',
      },
      fontFamily: {
        // The Scholar (scripture, headings) + The Librarian (UI)
        'display-scripture': ['"EB Garamond"', 'Georgia', 'serif'],
        'headline-lg': ['"EB Garamond"', 'Georgia', 'serif'],
        'headline-md': ['"EB Garamond"', 'Georgia', 'serif'],
        'study-title': ['"EB Garamond"', 'Georgia', 'serif'],
        'body-reading': ['"EB Garamond"', 'Georgia', 'serif'],
        'ui-label-lg': ['Inter', 'system-ui', 'sans-serif'],
        'ui-label-md': ['Inter', 'system-ui', 'sans-serif'],
        'ui-label-sm': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        // Base fonts reduced by 25%, study title reduced by 50%, with dynamic font scale multiplier
        'display-scripture': ['calc(25.5px * var(--font-scale, 1))', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg': ['calc(21px * var(--font-scale, 1))', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['calc(16.5px * var(--font-scale, 1))', { lineHeight: '1.3', fontWeight: '600' }],
        'study-title': ['calc(14px * var(--font-scale, 1))', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-reading': ['calc(15px * var(--font-scale, 1))', { lineHeight: '1.6', fontWeight: '400' }],
        'ui-label-lg': ['calc(12px * var(--font-scale, 1))', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '600' }],
        'ui-label-md': ['calc(10.5px * var(--font-scale, 1))', { lineHeight: '1.4', fontWeight: '500' }],
        'ui-label-sm': ['calc(9.5px * var(--font-scale, 1))', { lineHeight: '1.4', fontWeight: '500' }],
        'ui-label-xs': ['calc(8.5px * var(--font-scale, 1))', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-max': '1200px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'reading-width': '720px',
      },
      maxWidth: {
        'container-max': '1200px',
        'reading-width': '720px',
      },
      boxShadow: {
        'ambient': '0 4px 20px rgba(44, 62, 80, 0.05)',
        'ambient-lg': '0 8px 30px rgba(44, 62, 80, 0.08)',
        'ambient-top': '0 -10px 40px rgba(22, 40, 57, 0.05)',
      },
    },
  },
  plugins: [],
}
